#
# Copyright (c) 2021 Several Circles.
#
allAbout.1=...and that's what today is all about.
allAbout.2=That's it for today.
allAbout.3=What an exciting day!
author=%s
feeling=We're feeling
highUser=The highest scoring user is
quote=# %1$s\n\
*%2$s*a
quoteTitle=**%s had this to say:**
talkingAbout=We're talking about
title=Today
title.thanksgiving=Today, it's Thanksgiving, and
tomorrowBring.1=What will tomorrow bring?
tomorrowBring.2=Tomorrow is a new day.
tomorrowBring.3=Let's make tomorrow even better.